import streamlit as st
import pandas as pd

# Set page configuration
st.set_page_config(
    page_title="CodeCraft: AI Logic Explainer",
    page_icon="🧩",
    layout="wide"
)

# Custom CSS for a professional look
st.markdown("""
<style>
    .reportview-container {
        background: #f0f2f6;
    }
    .stCodeBlock {
        border-radius: 10px;
    }
    .explanation-card {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        border-left: 5px solid #4CAF50;
        box-shadow: 2px 2px 10px rgba(0,0,0,0.1);
    }
</style>
""", unsafe_allow_html=True)

st.title("🧩 CodeCraft: AI Logic Explainer")
st.markdown("### Translating Complex Code into Architectural Insights")

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("Input Code")
    language = st.selectbox("Select Language", ["Python", "JavaScript", "SQL", "Rust", "C++"])
    
    code_input = st.text_area("Paste your code snippet here:", height=300, placeholder="def complex_function(x): ...")
    
    analysis_depth = st.select_slider(
        "Analysis Depth",
        options=["Overview", "Line-by-Line", "Security Audit", "Performance Review"]
    )
    
    analyze_btn = st.button("Generate Explanation ✨", use_container_width=True)

with col2:
    st.subheader("AI Analysis")
    if analyze_btn and code_input:
        with st.spinner("Analyzing code structure and logic flows..."):
            # Simulation of AI processing
            import time
            time.sleep(1.5)
            
            st.markdown(f"**Depth Profile:** {analysis_depth}")
            
            st.markdown("""
            <div class="explanation-card">
                <h4>Logic Breakdown</h4>
                <p>This code implements a recursive pattern for data traversal with early exit conditions.</p>
                <ul>
                    <li><strong>Space Complexity:</strong> O(N) due to recursion stack depth.</li>
                    <li><strong>Risk Level:</strong> Low (Validated input types).</li>
                    <li><strong>Optimization Tip:</strong> Consider memoization for repeated sub-calls.</li>
                </ul>
            </div>
            """, unsafe_allow_html=True)
            
            st.subheader("Documentation Draft")
            st.code(f'"""\nAnalyzed {language} Snippet\nGenerated by CodeCraft AI v2.6\n"""', language="python")
    else:
        st.info("Paste code and click 'Generate' to see the AI breakdown.")

st.divider()
st.sidebar.markdown("## System Status")
st.sidebar.success("Model: GPT-4o-Turbo-2026")
st.sidebar.info("Latency: 240ms")

st.sidebar.markdown("""
---
**Project of guiltyfalcon's AI Portfolio**
[View Repository](https://github.com/guiltyfalcon/ai-portfolio)
""")
